import "dotenv/config";
import { db } from "@/lib/db";
import { organizationalUnits } from "@/db/schema";

// --- DATA DARI ANDA ---
const RAW_DIRECTORS = [
    "DIREKTUR UTAMA (DIRUT)",
    "DIREKTUR LEGAL DAN MANAJEMEN HUMAN CAPITAL (DIR LHC)",
    "DIREKTUR KEUANGAN (DIR KEU)",
    "DIREKTUR DISTRIBUSI (DIR DIST)",
    "DIREKTUR RETAIL DAN NIAGA (DIR RETAIL)",
    "DIREKTUR MANAJEMEN PROYEK DAN ENERGI BARU TERBARUKAN (DIR EBT)",
    "DIREKTUR PERENCANAAN KORPORAT DAN PENGEMBANGAN BISNIS (DIR RENBANG)",
    "DIREKTUR TRANSMISI DAN PERENCANAAN SISTEM (DIR TRANS)",
    "DIREKTUR MANAJEMEN PEMBANGKITAN (DIR MKIT)",
    "DIREKTUR MANAJEMEN RISIKO (DIR MRO)",
    "DIREKTUR TEKNOLOGI, ENGINEERING, DAN KEBERLANJUTAN (DIR TNK)"
];

const RAW_INITIATORS = [
    "KEPALA SATUAN PENGAWASAN INTERN (KSPI)",
    "EXECUTIVE VICE PRESIDENT STRATEGI AUDIT DAN KONSULTANSI (EVP SAK)",
    "EXECUTIVE VICE PRESIDENT AUDIT KONSTRUKSI, PEMBANGKIT, DAN EBT (EVP AKP)",
    "EXECUTIVE VICE PRESIDENT AUDIT TRANSMISI DAN DISTRIBUSI (EVP ATD)",
    "EXECUTIVE VICE PRESIDENT AUDIT NIAGA, TEKNOLOGI INFORMASI, DAN ENABLER (EVP ANT)",
    "EXECUTIVE VICE PRESIDENT AUDIT INVESTIGASI (EVP AIN)",
    "SEKRETARIS PERUSAHAAN (SEKPER)",
    "EXECUTIVE VICE PRESIDENT TRANSFORMASI KORPORAT DAN CEO OFFICE (EVP TCO)",
    "EXECUTIVE VICE PRESIDENT KOMUNIKASI KORPORAT DAN TJSL (EVP KOM)",
    "EXECUTIVE VICE PRESIDENT MANAJEMEN STAKEHOLDER DAN BOD SUPPORT (EVP SHB)",
    "KEPALA SATUAN DIGITAL DAN TEKNOLOGI INFORMASI (KSDTI)",
    "EXECUTIVE VICE PRESIDENT SISTEM DAN TEKNOLOGI INFORMASI (EVP STI)",
    "EXECUTIVE VICE PRESIDENT MANAJEMEN DIGITAL (EVP MDG)",
    "EXECUTIVE VICE PRESIDENT PROJECT MANAGEMENT OFFICE (EVP PMO)",
    "EXECUTIVE VICE PRESIDENT STRATEGI HUMAN CAPITAL (EVP HST)",
    "EXECUTIVE VICE PRESIDENT PELAYANAN HUMAN CAPITAL (EVP HSC)",
    "EXECUTIVE VICE PRESIDENT PENGEMBANGAN TALENTA (EVP HTD)",
    "EXECUTIVE VICE PRESIDENT UMUM DAN ASET PROPERTI (EVP MUM)",
    "EXECUTIVE VICE PRESIDENT KESELAMATAN, KESEHATAN KERJA, KEAMANAN, DAN LINGKUNGAN (EVP K3L)",
    "SENIOR EXECUTIVE VICE PRESIDENT HUKUM DAN KEBIJAKAN (SEVP HKK)",
    "EXECUTIVE VICE PRESIDENT KORPORASI DAN LEGAL BUSINESS PARTNER (EVP HLB)",
    "EXECUTIVE VICE PRESIDENT BANTUAN HUKUM (EVP HBK)",
    "EXECUTIVE VICE PRESIDENT REGULASI DAN KEBIJAKAN (EVP RKJ)",
    "EXECUTIVE VICE PRESIDENT LEGAL ASET PROPERTI DAN PERIZINAN TERINTEGRASI (EVP LPT)",
    "EXECUTIVE VICE PRESIDENT KEUANGAN KORPORAT (EVP KEU)",
    "EXECUTIVE VICE PRESIDENT ANGGARAN (EVP ANG)",
    "EXECUTIVE VICE PRESIDENT PERBENDAHARAAN (EVP PBH)",
    "EXECUTIVE VICE PRESIDENT AKUNTANSI (EVP AKT)",
    "EXECUTIVE VICE PRESIDENT MANAJEMEN VALUASI ASET (EVP MVA)",
    "EXECUTIVE VICE PRESIDENT PERENCANAAN STRATEGIS DISTRIBUSI (EVP RSD)",
    "EXECUTIVE VICE PRESIDENT OPERASI DISTRIBUSI SUMATERA DAN KALIMANTAN (EVP ODS)",
    "EXECUTIVE VICE PRESIDENT OPERASI DISTRIBUSI JAWA, MADURA, DAN BALI (EVP ODJ)",
    "EXECUTIVE VICE PRESIDENT OPERASI DISTRIBUSI SULAWESI, MALUKU, PAPUA, DAN NUSA TENGGARA (EVP ODM)",
    "EXECUTIVE VICE PRESIDENT PENGEMBANGAN LISTRIK DESA (EVP LDS)",
    "EXECUTIVE VICE PRESIDENT NIAGA DAN PEMASARAN (EVP NPS)",
    "EXECUTIVE VICE PRESIDENT CUSTOMER EXPERIENCE DAN EXCELLENCE SERVICES (EVP CES)",
    "EXECUTIVE VICE PRESIDENT PENGEMBANGAN PRODUK NIAGA (EVP PPN)",
    "EXECUTIVE VICE PRESIDENT PENJUALAN DAN PELAYANAN PELANGGAN RETAIL (EVP PPR)",
    "EXECUTIVE VICE PRESIDENT PENJUALAN DAN PELAYANAN PELANGGAN ENTERPRISE (EVP APR)",
    "EXECUTIVE VICE PRESIDENT PENGADAAN PEMBANGKIT DAN IPP (EVP PPI)",
    "EXECUTIVE VICE PRESIDENT PENGADAAN TRANSMISI, GARDU INDUK, DAN MATERIAL TERPUSAT (EVP MPT)",
    "EXECUTIVE VICE PRESIDENT MANAJEMEN RANTAI PASOK (EVP MRP)",
    "EXECUTIVE VICE PRESIDENT PENGEMBANGAN, PINJAMAN, DAN PERIZINAN PROYEK (EVP PPP)",
    "EXECUTIVE VICE PRESIDENT ENJINIRING DAN PERENCANAAN PENGADAAN (EVP MEP)",
    "EXECUTIVE VICE PRESIDENT KONSTRUKSI SUMATERA, KALIMANTAN DAN SULAWESI (EVP MKS)",
    "EXECUTIVE VICE PRESIDENT KONSTRUKSI JAWA, MADURA, BALI, MALUKU, PAPUA, DAN NUSA TENGGARA (EVP MKJ)",
    "EXECUTIVE VICE PRESIDENT ANEKA ENERGI BARU TERBARUKAN (EVP MEB)",
    "EXECUTIVE VICE PRESIDENT PANAS BUMI (EVP MPB)",
    "EXECUTIVE VICE PRESIDENT PERENCANAAN STRATEGIS KORPORAT (EVP RKO)",
    "EXECUTIVE VICE PRESIDENT MANAJEMEN PORTOFOLIO (EVP PFM)",
    "EXECUTIVE VICE PRESIDENT PENGENDALIAN KINERJA KORPORAT (EVP PKK)",
    "EXECUTIVE VICE PRESIDENT PENGEMBANGAN BISNIS KORPORAT DAN INVESTASI (EVP BKI)",
    "EXECUTIVE VICE PRESIDENT PERENCANAAN SISTEM KETENAGALISTRIKAN (EVP RSL)",
    "EXECUTIVE VICE PRESIDENT TRANSISI ENERGI DAN KEBERLANJUTAN (EVP TEK)",
    "EXECUTIVE VICE PRESIDENT OPERASI SISTEM KETENAGALISTRIKAN (EVP OSL)",
    "EXECUTIVE VICE PRESIDENT PERENCANAAN STRATEGIS TRANSMISI (EVP RST)",
    "EXECUTIVE VICE PRESIDENT TRANSMISI KALIMANTAN, SULAWESI, MALUKU, PAPUA, DAN NUSA TENGGARA (EVP TKS)",
    "EXECUTIVE VICE PRESIDENT TRANSMISI SUMATERA, JAWA, MADURA, DAN BALI (EVP TSJ)",
    "EXECUTIVE VICE PRESIDENT MANAJEMEN ASET, ENJINIRING DAN SISTEM MANAJEMEN TERINTEGRASI (EVP MES)",
    "EXECUTIVE VICE PRESIDENT PERENCANAAN STRATEGIS PEMBANGKITAN (EVP RSK)",
    "EXECUTIVE VICE PRESIDENT PENGENDALIAN PEMBANGKITAN DAN INDEPENDENT POWER PRODUCER (EVP DKI)",
    "EXECUTIVE VICE PRESIDENT OPERASI PEMBANGKITAN DAN INDEPENDENT POWER PRODUCER (EVP OKI)",
    "EXECUTIVE VICE PRESIDENT MANAJEMEN RISIKO FINANSIAL DAN ENABLER (EVP MRF)",
    "EXECUTIVE VICE PRESIDENT MANAJEMEN RISIKO OPERASI (EVP MRE)",
    "EXECUTIVE VICE PRESIDENT MANAJEMEN RISIKO STRATEGIS, REGULASI DAN KEBIJAKAN (EVP MRS)",
    "EXECUTIVE VICE PRESIDENT KEBIJAKAN STRATEGIS MANAJEMEN RISIKO (EVP KSM)",
    "EXECUTIVE VICE PRESIDENT KEPATUHAN (EVP PKP)",
    "EXECUTIVE VICE PRESIDENT LITIGASI DAN ADVOKASI (EVP HLA)",
    "EXECUTIVE VICE PRESIDENT OPERASI DAN PENGENDALIAN PEMBANGKITAN PLN GROUP (EVP OPP)",
    "EXECUTIVE VICE PRESIDENT OPERASI DAN PENGENDALIAN PEMBANGKITAN INDEPENDENT POWER PRODUCER (EVP OPI)",
    "EXECUTIVE VICE PRESIDENT MANAJEMEN ASET DAN SISTEM MANAJEMEN TERINTEGRASI (EVP MAS)",
    "EXECUTIVE VICE PRESIDENT TEKNOLOGI DAN ENJINERING (EVP TEN)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGKITAN DWIPANTARA (UIK DWP)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI YOGYAKARTA (UID YOGYA)"
];

const RAW_SUPPORT = [
    "PT PLN (PERSERO) UNIT INDUK PEMBANGKITAN TANJUNG JATI B (UIK TJB)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGUNAN SUMATERA BAGIAN UTARA (UIP SBU)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGUNAN SUMATERA BAGIAN TENGAH (UIP SBT)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGUNAN SUMATERA BAGIAN SELATAN (UIP SBS)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGUNAN KALIMANTAN BAGIAN BARAT (UIP KLB)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGUNAN KALIMANTAN BAGIAN TIMUR (UIP KLT)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGUNAN JAWA BAGIAN BARAT (UIP JBB)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGUNAN JAWA BAGIAN TENGAH (UIP JBT)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGUNAN JAWA BAGIAN TIMUR DAN BALI (UIP JBTB)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGUNAN NUSA TENGGARA (UIP NUSRA)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGUNAN SULAWESI (UIP SUL)",
    "PT PLN (PERSERO) UNIT INDUK PEMBANGUNAN MALUKU DAN PAPUA (UIP MPA)",
    "PT PLN (PERSERO) UNIT INDUK PENYALURAN DAN PUSAT PENGATUR BEBAN KALIMANTAN (UIP3B KAL)",
    "PT PLN (PERSERO) UNIT INDUK PENYALURAN DAN PUSAT PENGATUR BEBAN SULAWESI (UIP3B SUL)",
    "PT PLN (PERSERO) UNIT INDUK PENYALURAN DAN PUSAT PENGATUR BEBAN SUMATERA (UIP3B SUM)",
    "PT PLN (PERSERO) UNIT INDUK PUSAT PENGATUR BEBAN JAWA, MADURA, DAN BALI (UIP2B JAMALI)",
    "PT PLN (PERSERO) UNIT INDUK TRANSMISI JAWA BAGIAN BARAT (UIT JBB)",
    "PT PLN (PERSERO) UNIT INDUK TRANSMISI JAWA BAGIAN TENGAH (UIT JBT)",
    "PT PLN (PERSERO) UNIT INDUK TRANSMISI JAWA BAGIAN TIMUR DAN BALI (UIT JBM)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI JAKARTA RAYA (UID JAYA)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI BANTEN (UID BANTEN)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI JAWA BARAT (UID JABAR)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI JAWA TENGAH DAN D.I. YOGYAKARTA (UID JATENG)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI JAWA TIMUR (UID JATIM)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI BALI (UID BALI)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI LAMPUNG (UID LAMPUNG)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI ACEH (UID ACEH)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI SUMATERA UTARA (UID SUMUT)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI RIAU DAN KEPULAUAN RIAU (UID RKR)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI SUMATERA BARAT (UID SUMBAR)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI SUMATERA SELATAN, JAMBI DAN BENGKULU (UID S2JB)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI KALIMANTAN SELATAN DAN KALIMANTAN TENGAH (UID KALSELTENG)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI KALIMANTAN BARAT (UID KALBAR)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI KALIMANTAN TIMUR DAN KALIMANTAN UTARA (UID KALTIMRA)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI SULAWESI UTARA, SULAWESI TENGAH DAN GORONTALO (UID SULUTTENGGO)",
    "PT PLN (PERSERO) UNIT INDUK DISTRIBUSI SULAWESI SELATAN, SULAWESI TENGGARA DAN SULAWESI BARAT (UID SULSELRABAR)",
    "PT PLN (PERSERO) UNIT INDUK WILAYAH BANGKA BELITUNG (UIW BABEL)",
    "PT PLN (PERSERO) UNIT INDUK WILAYAH NUSA TENGGARA BARAT (UIW NTB)",
    "PT PLN (PERSERO) UNIT INDUK WILAYAH NUSA TENGGARA TIMUR (UIW NTT)",
    "PT PLN (PERSERO) UNIT INDUK WILAYAH MALUKU DAN MALUKU UTARA (UIW MMU)",
    "PT PLN (PERSERO) UNIT INDUK WILAYAH PAPUA DAN PAPUA BARAT (UIW PPB)",
    "PT PLN (PERSERO) PUSAT PENELITIAN DAN PENGEMBANGAN KETENAGALISTRIKAN (PUSLITBANG)",
    "PT PLN (PERSERO) PUSAT PEMELIHARAAN KETENAGALISTRIKAN (PUSHARLIS)",
    "PT PLN (PERSERO) PUSAT MANAJEMEN PROYEK (PUSMANPRO)",
    "PT PLN (PERSERO) PUSAT SERTIFIKASI (PUSERTIF)",
    "PT PLN (PERSERO) PUSAT PENDIDIKAN DAN PELATIHAN (CORPORATE UNIVERSITY) (PUSDIKLAT)",
    "PT PLN INDONESIA POWER (IP)",
    "PT PLN NUSANTARA POWER (NP)",
    "PT PLN ENERGI PRIMER INDONESIA (EPI)",
    "PT INDONESIA COMNETS PLUS (ICON)",
    "PT PLN ELECTRICITY SERVICES (ES)",
    "PT PLN NUSA DAYA (ND)",
    "PT PLN ENJINIRING (PLNE)",
    "PLT PLN BATAM (PLNB)",
    "PT ENERGY MANAGEMENT INDONESIA (EMI)",
    "PT PLN MANDAU CIPTA TENAGA NUSANTARA (MCTN)"
];

// Helper: Ekstrak kode dalam kurung. Contoh: "DIREKTUR UTAMA (DIRUT)" -> "DIRUT"
function extractCode(name: string): string | null {
    const match = name.match(/\(([^)]+)\)$/);
    // Menggunakan operator '?? null' untuk mengubah undefined menjadi null
    return (match && match[1]) ? match[1] : null;
}

async function main() {
    console.log("🌱 Seeding Unit Organisasi...");

    try {
        // Hapus data lama agar tidak duplikat (Opsional)
        // await db.delete(organizationalUnits);

        const allData = [
            ...RAW_DIRECTORS.map(name => ({ name, code: extractCode(name), category: "DIRECTOR" })),
            ...RAW_INITIATORS.map(name => ({ name, code: extractCode(name), category: "INITIATOR" })),
            ...RAW_SUPPORT.map(name => ({ name, code: extractCode(name), category: "SUPPORT" }))
        ];

        // Insert Batch
        await db.insert(organizationalUnits).values(allData);

        console.log(`✅ Berhasil memasukkan ${allData.length} data unit.`);
    } catch (error) {
        console.error("❌ Gagal seeding:", error);
    } finally {
        process.exit(0);
    }
}

main();